<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Images\Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\ic_info_dark.png" />
    <None Remove="Images\ic_info_light.png" />
    <None Remove="Images\ic_theme_dark.png" />
    <None Remove="Images\ic_theme_light.png" />
    <None Remove="Images\Logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\Icon.ico" />
    <Content Include="Images\ic_info_dark.png" />
    <Content Include="Images\ic_info_light.png" />
    <Content Include="Images\ic_theme_dark.png" />
    <Content Include="Images\ic_theme_light.png" />
    <Content Include="Images\Logo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0-rc2" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Backend\Backend.csproj" />
  </ItemGroup>

</Project>
